---
kind: pipeline
type: docker
name: default

steps:
  - name: check_repo_consistency
    image: golang:1.13
    commands:
      - go get github.com/rakyll/statik
      - make clean
      - make generated
      - bash -c "[[ `(git diff ; git add -fAn) | wc -l` -eq 0 ]] || ( git --no-pager diff; git add -fAn; echo Please run 'make generated' and commit again ; exit 1 )"
      - make fmt
      - bash -c "[[ `(git diff ; git add -fAn) | wc -l` -eq 0 ]] || ( git --no-pager diff; git add -fAn; echo Please run 'make fmt' and commit again ; exit 1 )"
      - make update_internal_packages
      - bash -c "[[ `(git diff ; git add -fAn) | wc -l` -eq 0 ]] || ( git --no-pager diff; git add -fAn; echo Please run 'make update_internal_packages' and commit again ; exit 1 )"
  - name: build
    image: golang:1.13
    commands:
      - make build
  - name: test
    image: golang:1.13
    commands:
      - make test
  - name: golangci-lint
    image: golangci/golangci-lint:v1.21.0
    commands:
      - make golangci-lint
  - name: crossbuild
    image: golang:1.13
    commands:
      - apt update
      - apt install -y zip
      - make crossbuild
  - name: publish_github
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_secret
      files:
        - '*.tar.gz'
        - '*.zip'
      checksum:
        - sha512
    when:
      event: tag
