---
kind: pipeline
type: docker
name: default

workspace:
  base: /go
  path: src/github.com/slrtbtfs/promql-lsp

steps:
  - name: check_repo_consistency
    image: golang:1.13
    commands:
      - go get github.com/rakyll/statik
      - make clean
      - make generated
      - bash -c "[[ `(git diff ; git add -fAn) | wc -l` -eq 0 ]] || ( git --no-pager diff; git add -fAn; echo Please run 'make generated' and commit again ; exit 1 )"
      - make fmt
      - bash -c "[[ `(git diff ; git add -fAn) | wc -l` -eq 0 ]] || ( git --no-pager diff; git add -fAn; echo Please run 'make fmt' and commit again ; exit 1 )"
      - make update_internal_packages
      - bash -c "[[ `(git diff ; git add -fAn) | wc -l` -eq 0 ]] || ( git --no-pager diff; git add -fAn; echo Please run 'make update_internal_packages' and commit again ; exit 1 )"
  - name: build
    image: golang:1.13
    commands:
      - go build cmd/
  - name: test
    image: golang:1.13
    commands:
      - go get ./cmd/...
      - make test
  - name: lint
    image: golang:1.13
    commands:
      - make lint