---
version: 2.1

jobs:
  build:
    docker:
      - image: circleci/golang:1.13-node
    working_directory: /go/src/github.com/slrtbtfs/promql-lsp
    steps:
      - checkout
      - run: go get github.com/slrtbtfs/go-tools-vendored/...
      - run: go get github.com/slrtbtfs/prometheus/promql
      - run: go build cmd/

  test:
    docker:
      - image: circleci/golang:1.13-node
    working_directory: /go/src/github.com/slrtbtfs/promql-lsp
    steps:
      - checkout
      - run: go get github.com/slrtbtfs/go-tools-vendored/...
      - run: go get github.com/slrtbtfs/prometheus/promql
      - run: make test

  check_repo_consistency:
    docker:
      - image: circleci/golang:1.13-node
    working_directory: /go/src/github.com/slrtbtfs/promql-lsp
    steps:
      - checkout
      - run: go get github.com/rakyll/statik
      - run: make clean
      - run: make generated
      - run: "[[ `git diff | wc -l` -eq 0 ]] || ( git --no-pager diff; echo Please run 'make generated' and commit again ; exit 1 )"
      - run: make fmt
      - run: "[[ `git diff | wc -l` -eq 0 ]] || ( git --no-pager diff; echo Please run 'make fmt' and commit again ; exit 1 )"
      - run: make update_internal_packages
      - run: "[[ `git diff | wc -l` -eq 0 ]] || ( git --no-pager diff; echo Please run 'make update_internal_packages' and commit again ; exit 1 )"

workflows:
  all:
    jobs:
      - check_repo_consistency
      - build
      - test
