---
version: 2.1

jobs:
  build:
    docker:
      - image: circleci/golang:1.13-node
    working_directory: /go/src/github.com/slrtbtfs/promql-lsp
    steps:
      - checkout
      - run: go get github.com/slrtbtfs/go-tools-vendored/...
      - run: go get github.com/slrtbtfs/prometheus/promql
      - run: go build cmd/

  test_if_generated_files_in_sync:
    docker:
      - image: circleci/golang:1.13-node
    working_directory: /go/src/github.com/slrtbtfs/promql-lsp
    steps:
      - checkout
      - run: go get github.com/rakyll/statik
      - run: make clean
      - run: make generated
      - run: "[[`git diff | wc -l` != 0 ]] && exit 1"

workflows:
  version: 2.1
  all:
    jobs:
      - test_if_generated_files_in_sync
      - build