---
version: 2.1

jobs:
  build:
    docker:
      - image: circleci/golang:1.13-node
    working_directory: /go/src/github.com/slrtbtfs/promql-lsp
    steps:
      - checkout
      - run: go get github.com/slrtbtfs/go-tools-vendored/...
      - run: go get github.com/slrtbtfs/prometheus/promql
      - run: go build cmd/

  check_if_generated_files_in_sync:
    docker:
      - image: circleci/golang:1.13-node
    working_directory: /go/src/github.com/slrtbtfs/promql-lsp
    steps:
      - checkout
      - run: go get github.com/rakyll/statik
      - run: sudo apt-get install git
      - run: make clean
      - run: make generated
      - run: "[[ `git diff | wc -l` -eq 0 ]] || {echo Please run 'make generated' and commit again && exit 1}"
  check_gofmt:
    docker:
      - image: circleci/golang:1.13-node
    working_directory: /go/src/github.com/slrtbtfs/promql-lsp
    steps:
      - checkout
      - run: make fmt
      - run: "[[ `git diff | wc -l` -eq 0 ]] || {echo Please run 'make fmt' and commit again && exit 1}" 

workflows:
  version: 2.1
  all:
    jobs:
      - check_if_generated_files_in_sync
      - check_gofmt
      - build